# Text of version/date "tags"
checkers.date.0=<!-- checker-framework-date -->
checkers.date.1=<!-- /checker-framework-date -->
checkers.zip.ver.0=<!-- checker-framework-zip-version -->
checkers.zip.ver.1=<!-- /checker-framework-zip-version -->
afu.zip.ver.0=<!-- annotation-tools-zip-version -->
afu.zip.ver.1=<!-- /annotation-tools-zip-version -->
release.info.0=ReleaseInfo}\\{
release.info.1=\\}
release.ver.0=ReleaseVersion}\\{
release.ver.1=\\}
