package org.checkerframework.javacutil;

import com.sun.source.tree.ClassTree;
import com.sun.source.tree.CompilationUnitTree;
import com.sun.source.tree.PackageTree;
import com.sun.source.util.JavacTask;
import com.sun.source.util.TaskEvent;
import com.sun.source.util.TaskListener;
import com.sun.source.util.TreePath;
import com.sun.source.util.Trees;
import com.sun.tools.javac.comp.CompileStates.CompileState;
import com.sun.tools.javac.main.JavaCompiler;
import com.sun.tools.javac.processing.JavacProcessingEnvironment;
import com.sun.tools.javac.util.Context;
import com.sun.tools.javac.util.Log;

import org.checkerframework.checker.nullness.qual.Nullable;
import org.checkerframework.dataflow.qual.SideEffectFree;

import java.util.HashSet;
import java.util.Set;

import javax.annotation.processing.AbstractProcessor;
import javax.annotation.processing.ProcessingEnvironment;
import javax.annotation.processing.Processor;
import javax.annotation.processing.RoundEnvironment;
import javax.lang.model.element.Element;
import javax.lang.model.element.ElementKind;
import javax.lang.model.element.Name;
import javax.lang.model.element.PackageElement;
import javax.lang.model.element.TypeElement;
import javax.lang.model.util.ElementFilter;

/**
 * This class is an abstract annotation processor designed to be a convenient superclass for
 * concrete "type processors", processors that require the type information in the processed source.
 *
 * <p>Type processing occurs in one round after the tool (e.g. Java compiler) analyzes the source
 * (all sources taken as input to the tool and sources generated by other annotation processors).
 *
 * <p>The tool infrastructure will interact with classes extending this abstract class as follows.
 *
 * <p>1-3 are identical to the {@link Processor} life cycle. 4-5 are unique to {@code
 * AbstractTypeProcessor} subclasses.
 *
 * <ol>
 *   <li>If an existing {@code Processor} object is not being used, to create an instance of a
 *       processor the tool calls the no-arg constructor of the processor class.
 *   <li>Next, the tool calls the {@link #init init} method with an appropriate {@code
 *       ProcessingEnvironment}.
 *   <li>Afterwards, the tool calls {@link #getSupportedAnnotationTypes
 *       getSupportedAnnotationTypes}, {@link #getSupportedOptions getSupportedOptions}, and {@link
 *       #getSupportedSourceVersion getSupportedSourceVersion}. These methods are only called once
 *       per run, not on each round.
 *   <li>For each class containing a supported annotation, the tool calls {@link
 *       #typeProcess(TypeElement, TreePath) typeProcess} method on the {@code Processor}. The class
 *       is guaranteed to be type-checked Java code and all the tree type and symbol information is
 *       resolved.
 *   <li>Finally, the tool calls the {@link #typeProcessingOver typeProcessingOver} method on the
 *       {@code Processor}.
 * </ol>
 *
 * <p>The tool is permitted to ask type processors to process a class once it is analyzed before the
 * rest of classes are analyzed. The tool is also permitted to stop type processing immediately if
 * any errors are raised, without invoking {@link #typeProcessingOver}.
 *
 * <p>The above describes the default, self-driven mode, in which this class registers its own
 * {@link TaskListener}. A host that already owns the compilation {@code TaskListener} can instead
 * call {@link #setExternallyDriven} and drive steps 4-5 itself; see {@link #typeProcessExternally}
 * and {@link #typeProcessingOverExternally}.
 *
 * <p>A subclass may override any of the methods in this class, as long as the general {@link
 * javax.annotation.processing.Processor Processor} contract is obeyed, with one notable exception.
 * {@link #process(Set, RoundEnvironment)} may not be overridden, as it is called during the
 * declaration annotation phase before classes are analyzed.
 */
public abstract class AbstractTypeProcessor extends AbstractProcessor {
    /**
     * The set of fully-qualified element names that should be type-checked. We store the names of
     * the elements, in order to prevent possible confusion between different Element
     * instantiations.
     */
    private final Set<Name> elements = new HashSet<>();

    /**
     * The fully-qualified names of the packages whose {@code package-info.java} is in this
     * compilation, and whose declaration should therefore be processed. Kept separately from {@link
     * #elements} because javac reports such a file's root element as a {@link PackageElement}, not
     * a {@link TypeElement}, so {@link ElementFilter#typesIn} does not see it.
     */
    private final Set<Name> packageElements = new HashSet<>();

    /**
     * Method {@link #typeProcessingStart()} must be invoked exactly once, before any invocation of
     * {@link #typeProcess(TypeElement, TreePath)}.
     */
    private boolean hasInvokedTypeProcessingStart = false;

    /**
     * Method {@link #typeProcessingOver} must be invoked exactly once, after the last invocation of
     * {@link #typeProcess(TypeElement, TreePath)}.
     */
    private boolean hasInvokedTypeProcessingOver = false;

    /** The TaskListener registered for completion of attribution. */
    private final AttributionTaskListener listener = new AttributionTaskListener();

    /**
     * Whether this processor is driven by an external host instead of by its own {@link
     * AttributionTaskListener}.
     *
     * <p>When {@code false} (the default), {@link #init(ProcessingEnvironment)} registers the
     * listener, which drives {@link #typeProcessingStart()}, {@link #typeProcess(TypeElement,
     * TreePath)}, and {@link #typeProcessingOver()}. This is the standard standalone
     * annotation-processor mode.
     *
     * <p>When {@code true}, no {@link TaskListener} is registered and a host drives that lifecycle,
     * preferably through {@link #typeProcessExternally(TypeElement, TreePath)} and {@link
     * #typeProcessingOverExternally()}, which handle the once-only bracketing. This is used when
     * the Checker Framework runs as an Error Prone plugin, because Error Prone already owns the
     * compilation {@link TaskListener}.
     *
     * @see #setExternallyDriven(boolean)
     */
    private boolean externallyDriven = false;

    /** Constructor for subclasses to call. */
    protected AbstractTypeProcessor() {}

    /**
     * Sets whether this processor is driven by an external host rather than by its own {@link
     * TaskListener}. Must be called before {@link #init(ProcessingEnvironment)}.
     *
     * <p>A host that embeds the Checker Framework (such as the Error Prone plugin bridge) calls
     * this with {@code true} and then drives the type-processing lifecycle through {@link
     * #typeProcessExternally(TypeElement, TreePath)} and {@link #typeProcessingOverExternally()}.
     *
     * @param externallyDriven true if a host will drive the type-processing lifecycle
     * @see #externallyDriven
     */
    public void setExternallyDriven(boolean externallyDriven) {
        if (processingEnv != null) {
            throw new BugInCF(
                    "setExternallyDriven must be called before init(ProcessingEnvironment);"
                            + " init has already run, so the self-driven TaskListener may already"
                            + " be registered.");
        }
        this.externallyDriven = externallyDriven;
    }

    /**
     * Returns true if a host drives this processor's type-processing lifecycle.
     *
     * @return true if a host drives the type-processing lifecycle
     * @see #setExternallyDriven(boolean)
     */
    protected final boolean isExternallyDriven() {
        return externallyDriven;
    }

    /**
     * {@inheritDoc}
     *
     * <p>In the default (self-driven) mode, registers a {@link TaskListener} that will get called
     * after FLOW. In externally-driven mode (see {@link #externallyDriven}), no {@link
     * TaskListener} is registered; the host drives the type-processing lifecycle instead.
     *
     * <p>The {@code shouldStopPolicy} is bumped to at least {@code FLOW} in both modes. The bump is
     * idempotent, so it is harmless if a host has already requested the same or a later stop
     * policy.
     */
    @Override
    public synchronized void init(ProcessingEnvironment env) {
        super.init(env);
        if (!externallyDriven) {
            JavacTask.instance(env).addTaskListener(listener);
        }
        Context ctx = ((JavacProcessingEnvironment) processingEnv).getContext();
        JavaCompiler compiler = JavaCompiler.instance(ctx);
        compiler.shouldStopPolicyIfNoError =
                CompileState.max(compiler.shouldStopPolicyIfNoError, CompileState.FLOW);
        compiler.shouldStopPolicyIfError =
                CompileState.max(compiler.shouldStopPolicyIfError, CompileState.FLOW);
    }

    /**
     * The use of this method is obsolete in type processors. The method is called during
     * declaration annotation processing phase only. It registers the names of elements to process.
     */
    @Override
    public final boolean process(
            Set<? extends TypeElement> annotations, RoundEnvironment roundEnv) {
        for (TypeElement elem : ElementFilter.typesIn(roundEnv.getRootElements())) {
            elements.add(elem.getQualifiedName());
        }
        for (PackageElement elem : ElementFilter.packagesIn(roundEnv.getRootElements())) {
            packageElements.add(elem.getQualifiedName());
        }
        return false;
    }

    /**
     * A method to be called once before the first call to typeProcess.
     *
     * <p>Subclasses may override this method to do any initialization work.
     */
    public void typeProcessingStart() {}

    /**
     * Processes a fully-analyzed class that contains a supported annotation (see {@link
     * #getSupportedAnnotationTypes()}).
     *
     * <p>The passed class is always valid type-checked Java code.
     *
     * @param element element of the analyzed class
     * @param tree the tree path to the element, with the leaf being a {@link ClassTree}
     */
    public abstract void typeProcess(TypeElement element, TreePath tree);

    /**
     * Processes a fully-analyzed package declaration, that is, the {@code package} clause of a
     * {@code package-info.java} in this compilation.
     *
     * <p>The {@code @Target} of an annotation may include {@link ElementKind#PACKAGE}, so a
     * declaration annotation and its contradictions can appear here exactly as they can on a class.
     * A {@code package-info.java} declares no type, however, so {@link #typeProcess} is never
     * invoked for one; this is the corresponding hook.
     *
     * <p>Does nothing by default. A subclass that has nothing to check on a package declaration
     * need not override it.
     *
     * @param element the analyzed package
     * @param tree the tree path to the package declaration, with the leaf being a {@link
     *     PackageTree}
     */
    public void packageProcess(PackageElement element, TreePath tree) {}

    /**
     * Returns the path to {@code cu}'s package declaration if {@code cu} is a {@code
     * package-info.java} -- a compilation unit that declares a package and no type -- and null
     * otherwise.
     *
     * <p>The compilation unit is what identifies such a file, rather than the type the ANALYZE
     * event carries. That type is not the same across versions: javac 21 reports {@code
     * <package>.package-info}, whose enclosing element is the package being declared, while javac
     * 11 and 17 report an anonymous type in the unnamed package, from which neither the package nor
     * its annotations can be reached. {@code Trees.getPath} returns null for it on every version,
     * so the path is built here in any case, with the {@link PackageTree} as its leaf to match
     * {@link #typeProcess}, whose path's leaf is the analyzed class's own declaration.
     *
     * @param cu a compilation unit
     * @return the path to {@code cu}'s package declaration, or null if {@code cu} declares a type
     */
    private @Nullable TreePath packageDeclarationPath(CompilationUnitTree cu) {
        PackageTree pkgTree = cu.getPackage();
        if (pkgTree == null || !cu.getTypeDecls().isEmpty()) {
            return null;
        }
        return new TreePath(new TreePath(cu), pkgTree);
    }

    /**
     * Invokes {@link #typeProcessingOver()} if every element this compilation registered has now
     * been processed.
     *
     * <p>Both sets must be empty: a compilation that contains classes and a {@code
     * package-info.java} may analyze the classes first, and ending type processing then would drop
     * the package declaration that has not been dispatched yet.
     */
    private void maybeInvokeTypeProcessingOver() {
        if (!hasInvokedTypeProcessingOver && elements.isEmpty() && packageElements.isEmpty()) {
            typeProcessingOver();
            hasInvokedTypeProcessingOver = true;
        }
    }

    /**
     * A method to be called once all the classes are processed.
     *
     * <p>Subclasses may override this method to do any aggregate analysis (e.g. generate report,
     * persistence) or resource deallocation.
     *
     * <p>Method {@link #getCompilerLog()} can be used to access the number of compiler errors.
     */
    public void typeProcessingOver() {}

    /**
     * Drives a single {@link #typeProcess(TypeElement, TreePath)} invocation on behalf of an
     * external host (see {@link #externallyDriven}), handling the once-only {@link
     * #typeProcessingStart()} bracketing.
     *
     * <p>Intended for hosts that own the compilation {@link TaskListener} (e.g. an Error Prone
     * plugin) and therefore cannot rely on this processor's own {@link AttributionTaskListener}.
     * The host must call {@link #typeProcessingOverExternally()} once, after the last class has
     * been processed.
     *
     * <p>Unlike the self-driven path, this method does not consult the {@link #elements} set (which
     * is only populated during the declaration annotation-processing round); the host is
     * responsible for deciding which classes to process and when processing is over.
     *
     * @param element element of the analyzed class
     * @param tree the tree path to the element, with the leaf being a {@link ClassTree}
     */
    public final void typeProcessExternally(TypeElement element, TreePath tree) {
        if (!hasInvokedTypeProcessingStart) {
            typeProcessingStart();
            hasInvokedTypeProcessingStart = true;
        }
        typeProcess(element, tree);
    }

    /**
     * Processes a package declaration on behalf of an external host (see {@link
     * #externallyDriven}), handling the once-only {@link #typeProcessingStart()} invocation.
     *
     * <p>The counterpart of {@link #typeProcessExternally} for a {@code package-info.java}. A host
     * needs it because the {@link TaskListener} that would otherwise dispatch the package
     * declaration is not registered in externally-driven mode.
     *
     * @param element the package being processed
     * @param tree the path to the package declaration, with the leaf being a {@link PackageTree}
     */
    public final void packageProcessExternally(PackageElement element, TreePath tree) {
        if (!hasInvokedTypeProcessingStart) {
            typeProcessingStart();
            hasInvokedTypeProcessingStart = true;
        }
        packageProcess(element, tree);
    }

    /**
     * Signals, on behalf of an external host (see {@link #externallyDriven}), that all classes have
     * been processed. Invokes {@link #typeProcessingOver()} exactly once. Also invokes {@link
     * #typeProcessingStart()} first if it has not yet run (e.g. if no classes were processed).
     *
     * @see #typeProcessExternally(TypeElement, TreePath)
     */
    public final void typeProcessingOverExternally() {
        if (!hasInvokedTypeProcessingStart) {
            typeProcessingStart();
            hasInvokedTypeProcessingStart = true;
        }
        if (!hasInvokedTypeProcessingOver) {
            typeProcessingOver();
            hasInvokedTypeProcessingOver = true;
        }
    }

    /**
     * Return the compiler log, which contains errors and warnings.
     *
     * @return the compiler log, which contains errors and warnings
     */
    @SideEffectFree
    public Log getCompilerLog() {
        return Log.instance(((JavacProcessingEnvironment) processingEnv).getContext());
    }

    /** A task listener that invokes the processor whenever a class is fully analyzed. */
    private final class AttributionTaskListener implements TaskListener {

        @Override
        public void finished(TaskEvent e) {
            if (e.getKind() != TaskEvent.Kind.ANALYZE) {
                return;
            }

            if (!hasInvokedTypeProcessingStart) {
                typeProcessingStart();
                hasInvokedTypeProcessingStart = true;
            }

            if (elements.isEmpty() && packageElements.isEmpty()) {
                maybeInvokeTypeProcessingOver();
            }

            if (e.getTypeElement() == null) {
                throw new BugInCF("event task without a type element");
            }
            if (e.getCompilationUnit() == null) {
                throw new BugInCF("event task without compilation unit");
            }

            TypeElement elem = e.getTypeElement();

            // javac synthesizes a "<package>.package-info" type for a package-info.java that
            // carries annotations, and fires ANALYZE for it.  That type was never a root element
            // -- the root element was the PackageElement -- so it is absent from `elements` and
            // the guard below would drop the event, leaving no way for any processor to reach a
            // package declaration.  Dispatch it to packageProcess instead, keyed on the package
            // this compilation actually contains.
            TreePath pkgPath = packageDeclarationPath(e.getCompilationUnit());
            if (pkgPath != null) {
                Element pkgEle = Trees.instance(processingEnv).getElement(pkgPath);
                if (pkgEle instanceof PackageElement
                        && packageElements.remove(((PackageElement) pkgEle).getQualifiedName())) {
                    packageProcess((PackageElement) pkgEle, pkgPath);
                    maybeInvokeTypeProcessingOver();
                    return;
                }
            }

            if (!elements.remove(elem.getQualifiedName())) {
                return;
            }

            TreePath p = Trees.instance(processingEnv).getPath(elem);

            typeProcess(elem, p);

            maybeInvokeTypeProcessingOver();
        }

        @Override
        public void started(TaskEvent e) {}
    }
}
